# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-19 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher_transaction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='pick_up_by',
        ),
        migrations.AddField(
            model_name='voucher',
            name='payment_options',
            field=models.CharField(choices=[('N/A', 'N/A'), ('Mail To Payee', 'Mail To Payee'), ('Pick Up By', 'Pick Up By')], default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='delivery_type',
            field=models.CharField(choices=[('N/A', 'N/A'), ('Vender Payment', 'Vender Payment'), ('Reimbursement', 'Reimbursement'), ('Transfers', 'Transfers')], default='N/A', max_length=200),
        ),
    ]
