# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-20 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher_transaction', '0002_auto_20170619_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='formid',
            field=models.CharField(default='N/A', max_length=400),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='date_1',
            field=models.FloatField(default='N/A', max_length=500),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='delivery_type',
            field=models.CharField(choices=[('N/A', 'N/A'), ('Vendor Payment', 'Vendor Payment'), ('Reimbursement', 'Reimbursement'), ('Transfers', 'Transfers')], default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='expense_amount_1',
            field=models.FloatField(default=0),
        ),
    ]
