# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-20 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher_transaction', '0003_auto_20170620_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='date_2',
            field=models.CharField(default='N/A', max_length=500),
        ),
        migrations.AddField(
            model_name='voucher',
            name='date_3',
            field=models.CharField(default='N/A', max_length=500),
        ),
        migrations.AddField(
            model_name='voucher',
            name='date_4',
            field=models.CharField(default='N/A', max_length=500),
        ),
        migrations.AddField(
            model_name='voucher',
            name='expense_amount_2',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='voucher',
            name='expense_amount_3',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='voucher',
            name='expense_amount_4',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='voucher',
            name='expense_descript_2',
            field=models.CharField(default='N/A', max_length=500),
        ),
        migrations.AddField(
            model_name='voucher',
            name='expense_descript_3',
            field=models.CharField(default='N/A', max_length=500),
        ),
        migrations.AddField(
            model_name='voucher',
            name='expense_descript_4',
            field=models.CharField(default='N/A', max_length=500),
        ),
        migrations.AddField(
            model_name='voucher',
            name='expense_invoice_2',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='voucher',
            name='expense_invoice_3',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='voucher',
            name='expense_invoice_4',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='voucher',
            name='expense_type_2',
            field=models.CharField(choices=[('N/A', 'N/A'), ('5000', '5000 Office - Advertising/Printing/Etc.'), ('5010', '5010 Office - Food'), ('5020', '5020 Office - Gifts (Seniors/advisors/etc)'), ('5030', '5030 Office - Miscellaneous Supplies'), ('5040', '5040 Office - Bank Fees'), ('5100', '5100 Equipment/Supplies'), ('5200', '5200 Clothing/Uniforms'), ('5300', '5300 Medical Supplies'), ('5400', '5400 Payroll - Admin'), ('5410', '5410 Payroll - Student Employment'), ('5420', '5420 Stipends'), ('5500', '5500 Telephone'), ('5600', '5600 Insurance'), ('5605', '5605 Insurance - HF'), ('5700', '5700 Legal Fees'), ('5705', '5705 Legal Clinics'), ('5710', '5710 Auditing Fees'), ('5720', '5720 Bookkeeping Fees'), ('5725', '5725 Admin Fees'), ('5730', '5730 IT Support'), ('5750', '5750 Tax Expense'), ('5800', '5800 Training Cost'), ('5801', '5801 CPR Training'), ('5802', '5802 Training Conference - HF'), ('6000', '6000 Events - Advertising/Printing/Etc.'), ('6100', '6100 Events - Food'), ('6200', '6200 Events - Gifts/Prizes/Favors'), ('6300', '6300 Events - Miscellaneuos Expense'), ('6400', '6400 Events - Clothing/Uniforms'), ('6500', '6500 Events - Staffing(Univ/Campus Life/Event Ctr/etc)'), ('6600', '6600 Events - Rentals/Decorations/etc.'), ('6700', '6700 Events - Entertainer/Speaker/etc.'), ('6800', '6800 Events - Entertainment (rides/etc)'), ('7000', '7000 Travel - Transportation'), ('7100', '7100 Travel - Lodging'), ('7200', '7200 Travel - Fuel'), ('7300', '7300 Travel - Registration Fees'), ('7400', '7400 Donations'), ('7500', '7500 Co-Sponsorship'), ('7900', '7900 Other Expense'), ('8000', '8000 Vehicles - Registration'), ('8100', '8100 Vehicles - Fuel'), ('8200', '8200 Vehicles - Repairs & Maintainence'), ('8201', '8201 Oxygen - HF'), ('8202', '8202 Stretchers and Lifepak Maintainence - HF'), ('8203', '8203 Radios and Technology - HF'), ('8204', '8204 Software - HF'), ('8300', '8300 Vehicles - Purchase'), ('8400', '8400 Depreciation'), ('8500', '8500 University Support - Expense'), ('9000', '9000 Transfers')], default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='voucher',
            name='expense_type_3',
            field=models.CharField(choices=[('N/A', 'N/A'), ('5000', '5000 Office - Advertising/Printing/Etc.'), ('5010', '5010 Office - Food'), ('5020', '5020 Office - Gifts (Seniors/advisors/etc)'), ('5030', '5030 Office - Miscellaneous Supplies'), ('5040', '5040 Office - Bank Fees'), ('5100', '5100 Equipment/Supplies'), ('5200', '5200 Clothing/Uniforms'), ('5300', '5300 Medical Supplies'), ('5400', '5400 Payroll - Admin'), ('5410', '5410 Payroll - Student Employment'), ('5420', '5420 Stipends'), ('5500', '5500 Telephone'), ('5600', '5600 Insurance'), ('5605', '5605 Insurance - HF'), ('5700', '5700 Legal Fees'), ('5705', '5705 Legal Clinics'), ('5710', '5710 Auditing Fees'), ('5720', '5720 Bookkeeping Fees'), ('5725', '5725 Admin Fees'), ('5730', '5730 IT Support'), ('5750', '5750 Tax Expense'), ('5800', '5800 Training Cost'), ('5801', '5801 CPR Training'), ('5802', '5802 Training Conference - HF'), ('6000', '6000 Events - Advertising/Printing/Etc.'), ('6100', '6100 Events - Food'), ('6200', '6200 Events - Gifts/Prizes/Favors'), ('6300', '6300 Events - Miscellaneuos Expense'), ('6400', '6400 Events - Clothing/Uniforms'), ('6500', '6500 Events - Staffing(Univ/Campus Life/Event Ctr/etc)'), ('6600', '6600 Events - Rentals/Decorations/etc.'), ('6700', '6700 Events - Entertainer/Speaker/etc.'), ('6800', '6800 Events - Entertainment (rides/etc)'), ('7000', '7000 Travel - Transportation'), ('7100', '7100 Travel - Lodging'), ('7200', '7200 Travel - Fuel'), ('7300', '7300 Travel - Registration Fees'), ('7400', '7400 Donations'), ('7500', '7500 Co-Sponsorship'), ('7900', '7900 Other Expense'), ('8000', '8000 Vehicles - Registration'), ('8100', '8100 Vehicles - Fuel'), ('8200', '8200 Vehicles - Repairs & Maintainence'), ('8201', '8201 Oxygen - HF'), ('8202', '8202 Stretchers and Lifepak Maintainence - HF'), ('8203', '8203 Radios and Technology - HF'), ('8204', '8204 Software - HF'), ('8300', '8300 Vehicles - Purchase'), ('8400', '8400 Depreciation'), ('8500', '8500 University Support - Expense'), ('9000', '9000 Transfers')], default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='voucher',
            name='expense_type_4',
            field=models.CharField(choices=[('N/A', 'N/A'), ('5000', '5000 Office - Advertising/Printing/Etc.'), ('5010', '5010 Office - Food'), ('5020', '5020 Office - Gifts (Seniors/advisors/etc)'), ('5030', '5030 Office - Miscellaneous Supplies'), ('5040', '5040 Office - Bank Fees'), ('5100', '5100 Equipment/Supplies'), ('5200', '5200 Clothing/Uniforms'), ('5300', '5300 Medical Supplies'), ('5400', '5400 Payroll - Admin'), ('5410', '5410 Payroll - Student Employment'), ('5420', '5420 Stipends'), ('5500', '5500 Telephone'), ('5600', '5600 Insurance'), ('5605', '5605 Insurance - HF'), ('5700', '5700 Legal Fees'), ('5705', '5705 Legal Clinics'), ('5710', '5710 Auditing Fees'), ('5720', '5720 Bookkeeping Fees'), ('5725', '5725 Admin Fees'), ('5730', '5730 IT Support'), ('5750', '5750 Tax Expense'), ('5800', '5800 Training Cost'), ('5801', '5801 CPR Training'), ('5802', '5802 Training Conference - HF'), ('6000', '6000 Events - Advertising/Printing/Etc.'), ('6100', '6100 Events - Food'), ('6200', '6200 Events - Gifts/Prizes/Favors'), ('6300', '6300 Events - Miscellaneuos Expense'), ('6400', '6400 Events - Clothing/Uniforms'), ('6500', '6500 Events - Staffing(Univ/Campus Life/Event Ctr/etc)'), ('6600', '6600 Events - Rentals/Decorations/etc.'), ('6700', '6700 Events - Entertainer/Speaker/etc.'), ('6800', '6800 Events - Entertainment (rides/etc)'), ('7000', '7000 Travel - Transportation'), ('7100', '7100 Travel - Lodging'), ('7200', '7200 Travel - Fuel'), ('7300', '7300 Travel - Registration Fees'), ('7400', '7400 Donations'), ('7500', '7500 Co-Sponsorship'), ('7900', '7900 Other Expense'), ('8000', '8000 Vehicles - Registration'), ('8100', '8100 Vehicles - Fuel'), ('8200', '8200 Vehicles - Repairs & Maintainence'), ('8201', '8201 Oxygen - HF'), ('8202', '8202 Stretchers and Lifepak Maintainence - HF'), ('8203', '8203 Radios and Technology - HF'), ('8204', '8204 Software - HF'), ('8300', '8300 Vehicles - Purchase'), ('8400', '8400 Depreciation'), ('8500', '8500 University Support - Expense'), ('9000', '9000 Transfers')], default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='date_1',
            field=models.CharField(default='N/A', max_length=500),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='expense_amount_1',
            field=models.CharField(default='', max_length=10),
        ),
    ]
