# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-20 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher_transaction', '0008_auto_20170620_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='expense_amount_1',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='expense_amount_2',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='expense_amount_3',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='expense_amount_4',
            field=models.CharField(default='N/A', max_length=10),
        ),
    ]
